config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: "candidates#index"
  end
  
  unauthenticated :user do
    root "pages#home"
  end
  get 'pages/home'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations, :password]
  resources :candidates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

end

app/models/candidate.rb
class Candidate < ApplicationRecord
    belongs_to :user
    has_many :education_levels, dependent: :delete_all
    accepts_nested_attributes_for :education_levels,
                                  allow_destroy: true,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }
    has_many :skills, dependent: :delete_all
    accepts_nested_attributes_for :skills, 
                                  allow_destroy: true,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }
    has_many :careers, dependent: :delete_all
    accepts_nested_attributes_for :careers, 
                                  allow_destroy: true,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }
    has_many :languages, dependent: :delete_all                                  
    accepts_nested_attributes_for :languages, 
                                  allow_destroy: true,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }
    has_many :performance_areas, dependent: :delete_all                                  
    accepts_nested_attributes_for :performance_areas, 
                                  allow_destroy: true,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }
    has_many :industries, dependent: :delete_all                                  
    accepts_nested_attributes_for :industries, 
                                   allow_destroy: true,
                                   reject_if: lambda { |attrs| attrs['name'].blank? }                                                     
                              

    GENRE_LIST = ["Masculino", "Femenino"]
    EDUCATION_LEVEL = ["Bachiller", "Estudiante Universitario", "Técnico", "Diplomado", "Licenciatura", "Ingenieria", "Maestria", "Postgrado", "MBA", "Doctorado", "PHD"]
    STATUS = ["Empleado", "Desempleado", "No disponible", "Sin Asignar"] 
    CAREERS = ["", "Administración", "Administración de Negocios", "Administración/Gestión Pública", "Aeroespacial", "Agronomía", "Alimentos", 
            "Anestesiología/Inhaloterapia", "Arqueología", "Arquitectura", "Arte Dramático", "Automotriz", "Aviación","Bellas Artes", "Bibliotecología/Documentación",
            "Biología", "Biología Marina", "Biomédica", "Bioquímica", "Ciencias Juridicas / Jurisprudencia", "Civil/Minas", 
            "Comercio Internacional/Exterior", "Computación/Sistemas", "Contabilidad/Auditoría", "Cosmetología", "Comunicaciones", "Crimonología", 
            "Danza", "Dibujo Técnico", "Diseño de Vestuario/Textil/Modas", "Diseño Gráfico", "Diseño Industrial", "Diseño Interior/ Ambiental/Paisajismo",
            "Ecología", "Economía", "Educación Básica/Primaria", "Educacion especial", "Educacion especial/Diferencial/Sicopedagogia",
            "Educación Física/Deporte", "Educación Parvularia/Inicial", "Electrica", "Electronica/ Electromecanica", 
            "Enfermería", "Estadísticas", "Filosofía", "Finanzas", "Finanzas Bancarias", "Física", "Fisioterapia", 
            "Fotografía", "Gastronomía/Cocina", "Geología/Cartografia/Topografía", "Hidráulica", "Hotelería", 
            "Idiomas", "Impuestos Internacionales", "Industrial", "Laboratorio Clínico", "Matemáticas", "Mecánica/Metalurgica",
            "Mecatronica/Automatizacion", "Medicina", "Mercadeo/Mercadotecnia", "Música", "Naval", "Negocios internacionales", 
            "Negocios/Economia/Industrial", "Nutrición", "Periodismo", "Pesquera/Cultivos", "Política", "Publicidad", 
            "Quimica", "Química y Farmacia", "Radiología", "Recursos Humanos/Relac. Ind.", "Relaciones Internacionales", 
            "Relaciones Públicas", "Responsabilidad Social Corporativa", "Salud Ambiental (Ecotecnologo)", "Secretariado/administración",
            "Seguridad Industrial/Ocupacional", "Sicología", "Sociología", "Tecnología Médica", "Telecomunicaciones", "Teologia/Pastoral",
            "Terapia Ocupacional", "Prevención de accidentes", "Textil", "Transporte", "Turismo", "Veterinaria/Zootecnia", 
            "Logística"]
    LANGUAGES = ["Inglés-Básico", "Inglés-Intermedio", "Inglés-Avanzado", "Francés-Básico", "Francés-Intermedio",
         "Francés-Avanzado", "Alemán-Basico", "Alemán-Intermedio", "Alemán-Avanzado", "Portugués-Básico", "Portugués-Intermedio",
         "Portugués-Avanzado", "Otros"]
    PERFORMANCE_AREAS = ["Administración","Calidad","Comercial / Ventas","Comunicaciones","Diseño / Fotografía / Multimedia",
        "Educación / Docencia / Investigación","Electricidad","Energía Renovables","Finanzas / Contabilidad","Gastronomía / Turismo",
        "Gobierno","Ingenierías","Legales","Logística / Distribución (Supply Chain)","Mercadeo / Publicidad","Minería / Petroleo / Gas",
        "Operaciones Bodega/Alamacen","Otra(s) área(s)","Producción / Manufactura","Recursos Humanos","Riesgos","Salud / Medicina / Farmacia",
        "Seguridad Industrial / Ocupacional","Servicio al Cliente","Tecnología / Sistemas / Computación","Telecomunicaciones / Redes"]   
    INDUSTRY = ["Aérea", "Agro-Industrial", "Agropecuaria", "Alimenticia", "Arquitectura", "Artesanal", "Automotriz", 
        "Banca/Financiera", "Biotecnología", "Call Center", "Calzado", "Comercio", "Comercio Exterior", "Construcción", 
        "Consultoria", "Consumo Masivo", "Defensa", "Diseño", "Editorial", "Educación", "Energía", "Entretenimiento", 
        "Farmacéutica", "Ferroviaria", "Financiera", "Forestal", "Ganadera", "Gastronómica", "Gobierno", "Higiene y Salud",
        "Holding", "Hoteleria", "Immobiliaria", "Imprenta", "Industrias", "Informacion e Investigacion", "Informatica/Tecnología", 
        "Internet", "Jurídica", "Laboratorio", "Manufactura", "Medios", "Minería/Petroleo/Gas", "Naviera/Transporte",
        "ONGs", "Otra", "Papelería", "Pesca", "Plasticos", "Publicidad/Marketing/RRPP", "Química", "Retail", "Salud", 
        "Seguros", "Servicios", "Super Mercado/Hipermercado", "Tabacalera", "Telecomunicaciones", "Textil", "Transporte", 
        "Turismo"]
    REGIONAL_CANDIDATE = ["No", "Si"]
    CIVIL_STATUS = ["Soltero", "Casado", "Unión libre", "Divorciado", "Viudo"]
    SKILLS = [".NET", "Abogado", "AFTER EFFECTS", "AMAZON-S3", "AS400", "Auditor", "Big Data", "BLACK BELT", "BPM", 
        "Business Intelligence", "C#", "Category Management", "CCNA", "CCNP", "CLOUD COMPUTING", "COBIT", "CRM", 
        "CSC", "DEBIAN", "DJANGO", "Dynamic", "Energías Renovables", "ERP", "Exactus", "FEDORA", "FIFO", 
        "Generación/ distribución electricidad", "GOGNOS", "Google Adwords Redes Sociales", "Google Analytics",
        "GREEN BELT", "HACCP", "Hay", "HEROKU", "HTML", "ILLUSTRATOR", "IN DESIGN", "IN DESING", "Ingles legal",
        "Investigación y Desarrollo", "IPV4", "IPV6", "ISO", "ISO 14000", "ISO 22000", "ISO 27000", "ISO9000", 
        "ISO9001", "ITIL", "Java", "JED", "KANBAN", "LAN", "LINUX", "NIELSEN", "Notario publico", "Oracle", "OSHA",
        "OTROS ERP", "Peachtree", "PHOTOSHOP", "PHP", "PLC", "PMI", "PMO", "PMP", "POP", "POWER BI", "PREMIER PRO",
        "PYTHON", "REDHAT", "RESTFUL", "RUBY ON RAILS", "SAP", "SCRUM", "SIX SIGMA", "SLA", "SOA", "SQL", 
        "SQL-SERVER", "SSAS", "SSP", "SSRS", "Tableau.Excel", "UBUNTU", "UI/UX", "VB", "VIRTUALIZACION", 
        "Visual Hur", "VISUAL STUDIO", "WAN", "WINDOWS SERVER", "YELLOW BELT"]
    RECRUITMENT_SOURCE = ["Hunting", "Bolsa de empleo en línea", "Redes sociales Search", "Página de Search", 
        "Referido", "Linkedin", "Bolsas de empleo", "Universidades", "Grupo o gremios Especializados"]
    RELOCATE = ["No", "Si"]
    COUNTRIES = ["Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia",
     "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania", 
     "Bolivia", "Bosnia-Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", 
     "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Colombia", "Comoras", "Congo", "Corea del Norte", "Corea del Sur", 
     "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", 
     "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", 
     "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guinea", "Guinea Ecuatorial", "Guinea-Bisáu", "Guyana", "Haití", "Honduras", 
     "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", 
     "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kosovo", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", 
     "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macedonia", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos",
     "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", 
     "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Palestina", "Panamá", 
     "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana", "República Checa", 
     "República Democrática del Congo", "República Dominicana", "Ruanda", "Rumania", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", 
     "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria",
     "Somalia", "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Taiwán", "Tanzania",

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.where(user_id: current_user.id)
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = current_user.candidates.new(candidate_params)
    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :cellphone, :birth_date, :genre, :status, :regional_candidate, :country_code,
                                        :civil_status, :recruitment_source, :relocate, :actual_salary, :email,
                                        :variable_salary, :wage_aspiration, :position, :comparative_chart, :specific_benefit,
                                        :general_benefits, :general_comments, :address, :conditions_to_move, :telephone,
                                        :interview_date, :nationality, :actual_company, skills_attributes: [:id, :name, :_destroy],
                                        education_levels_attributes: [:id, :name, :_destroy], 
                                        careers_attributes: [:id, :name, :_destroy], languages_attributes: [:id, :name, :_destroy],
                                        performance_areas_attributes: [:id, :name, :_destroy], industries_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_career_fields.html.erb
<div class="form-group nested-fields">
    <div class="input-group mb-1">
        <div class="input-group-prepend">
          <%= f.label :name, "Carrera", class: "input-group-text" %>
        </div>
        <%= f.select(:name, Candidate::CAREERS, {} ,{class: 'form-control text-center'}) %>
        <%= link_to_remove_association 'Eliminar carrera', f, class: 'btn btn-danger' %>
    </div>
</div>    
   

app/views/candidates/_education_level_fields.html.erb
<div class="form-group nested-fields">
    <div class="input-group mb-1">
        <div class="input-group-prepend">
            <%= f.label :name, "Nivel educativo", class: "input-group-text" %>
        </div>
        <%= f.select(:name, Candidate::EDUCATION_LEVEL, {} ,{class: 'form-control text-center'}) %>
        <%= link_to_remove_association 'Eliminar nivel educativo', f, class: 'btn btn-danger' %>
    </div>
</div>

app/views/candidates/_industry_fields.html.erb
<div class="form-group nested-fields">
    <div class="input-group mb-1">
        <div class="input-group-prepend">
          <%= f.label :name, "Industria", class: "input-group-text" %>
        </div>
        <%= f.select(:name, Candidate::INDUSTRY, {} ,{class: 'form-control text-center'}) %>
        <%= link_to_remove_association 'Eliminar', f, class: 'btn btn-danger' %>
      </div>
</div>

app/views/candidates/_language_fields.html.erb
<div class="form-group nested-fields">
    <div class="input-group mb-1">
        <div class="input-group-prepend">
            <%= f.label :name, "Idiomas", class: "input-group-text" %>
        </div>
        <%= f.select(:name, Candidate::LANGUAGES, {} ,{class: 'form-control text-center'}) %>
        <%= link_to_remove_association 'Eliminar idioma', f, class: 'btn btn-danger' %>
    </div>
</div>

app/views/candidates/_performance_area_fields.html.erb
<div class="form-group nested-fields">
    <div class="input-group mb-1">
        <div class="input-group-prepend">
          <%= f.label :name, "Áreas de desempeño", class: "input-group-text" %>
        </div>
        <%= f.select(:name, Candidate::PERFORMANCE_AREAS, {} ,{class: 'form-control text-center'}) %>
        <%= link_to_remove_association 'Eliminar área de desempeño', f, class: 'btn btn-danger' %>
    </div>
</div>

app/views/candidates/_skill_fields.html.erb
<div class="form-group nested-fields">
    <div class="input-group mb-1">
        <div class="input-group-prepend">
            <%= f.label :name, "Skills", class: "input-group-text" %>
        </div>
        <%= f.select(:name, Candidate::SKILLS, {} ,{class: 'form-control text-center'}) %>
        <%= link_to_remove_association 'Eliminar skill', f, class: 'btn btn-danger' %>
    </div>
</div>

app/views/candidates/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="text-white">Editar candidato</h1>

      <div class="card text-white bg-light m-2 p-2">
        <%= render 'form', candidate: @candidate %>
      </div>

      <div class="btn-group mb-2">
        <%= link_to 'Ver', @candidate, class: "btn btn-success" %>
        <%= link_to 'Regresar', candidates_path, class: "btn btn-light"%>
      </div>

    </div>
  </div>
</div>

app/views/candidates/index.html.erb
<div class="container mb-2">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>
      

      <h1 class="text-white">Candidatos</h1>

      <div class="table-responsive">
        <table class="table table-striped text-white">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Nombre</th>
              <th scope="col">Celular</th>
              <th scope="col">Fecha de nacimiento</th>
              <th scope="col">Talent Hunter</th>
              <th scope="col">Género</th>
              <th scope="col">Nivel educativo</th>
              <th scope="col">Carrera</th>
              <th scope="col">Estatus</th>
              <th scope="col">Idiomas</th>
              <th scope="col">Áreas de desempeño</th>
              <th scope="col">Industria</th>
              <th scope="col">Candidato regional</th>
              <th scope="col">Estado civil</th>
              <th scope="col">Skills</th>
              <th scope="col">Dispuesto a reubicarse</th>
              <th scope="col">Fuente de reclutamiento</th>
              <th scope="col">Salario actual / Último salario (USD)</th>
              <th scope="col">Salario variable (USD)</th>
              <th scope="col">Aspiración salarial (USD)</th>
              <th scope="col">Posición / Cargo actual</th>
              <th scope="col">Datos cuadro comparativo</th>
              <th scope="col">Beneficio específico</th>
              <th scope="col">Beneficios generales</th>
              <th scope="col">Comentarios generales</th>
              <th scope="col">Dirección</th>
              <th scope="col">Condiciones para moverse</th>
              <th scope="col">Teléfono de casa</th>
              <th scope="col">Fecha de entrevista</th>
              <th scope="col">Nacionalidad</th>
              <th scope="col">País</th>
            </tr>
          </thead>

          <tbody>
            <% @candidates.each do |can| %>
              <tr>
                <td>
                  <div class="btn-group" role="group">
                    <%= link_to 'Editar', edit_candidate_path(can), class: "btn btn-warning" %>
                    <%= link_to 'Eliminar', can, method: :delete, data: { confirm: '¿Está seguro que desea eliminar el candidato?' }, class: "btn btn-danger" %>
                  </div>
                </td>
                <td><%= can.name %></td>
                <td><%= can.cellphone %></td>
                <td><%= can.birth_date.strftime("%d-%m-%Y") %></td>
                <td><%= can.user.name %></td>
                <td><%= can.genre %></td>
                <td>
                  <% can.education_levels.each do |e| %>
                    <p><%= e.name %></p>
                  <% end %>
                </td>
                <td>
                  <% can.careers.each do |c| %>
                    <p><%= c.name %></p>
                  <% end %>
                </td>
                <td><%= can.status %></td>
                <td>
                  <% can.languages.each do |l| %>
                    <p><%= l.name %></p>
                  <% end %>
                </td>
                <td>
                  <% can.performance_areas.each do |p| %>
                    <p><%= p.name %></p>
                  <% end %>
                </td>
                <td>
                  <% can.industries.each do |i| %>
                    <p><%= i.name %></p>
                  <% end %>
                </td>
                <td><%= can.regional_candidate %></td>
                <td><%= can.civil_status %></td>
                <td>
                  <% can.skills.each do |s| %>
                    <p><%= s.name %></p>
                  <% end %>
                </td>
                <td><%= can.relocate %></td>
                <td><%= can.recruitment_source %></td>
                <td><%= can.actual_salary %></td>
                <td><%= can.variable_salary %></td>
                <td><%= can.wage_aspiration %></td>
                <td><%= can.position %></td>
                <td><%= can.comparative_chart %></td>
                <td><%= can.specific_benefit %></td>
                <td><%= can.general_benefits %></td>
                <td><%= can.general_comments %></td>
                <td><%= can.address %></td>
                <td><%= can.conditions_to_move %></td>
                <td><%= can.telephone %></td>
                <td><%= can.interview_date.strftime("%d-%m-%Y")  %></td>
                <td><%= can.nationality %></td>
                <td><%= can.country_code %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <br>

      <%= link_to 'Agregar nuevo candidato', new_candidate_path, class: "btn btn-success" %>

    </div>
  </div>
</div>

app/views/candidates/new.html.erb
<div class="container mb-2">
    <div class="row">
        <div class="col">
            <h1 class="text-white">Agregar nuevo candidato</h1>

            <div class="card text-white bg-light m-2 p-2">
                <%= render 'form', candidate: @candidate %>
            </div>

            <%= link_to 'Regresar', candidates_path, class: "btn btn-light"%>

        </div>
    </div>
</div>

app/views/candidates/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <p id="notice"><%= notice %></p>
        <div class="card text-white bg-dark m-2 p-2">
            <p>
                <strong>Nombre completo:</strong>
                <%= @candidate.name %>
              </p>
              
              <p>
                <strong>Celular:</strong>
                <%= @candidate.cellphone %>
              </p>
              
              <p>
                <strong>Fecha de nacimiento:</strong>
                <%= @candidate.birth_date %>
              </p>
              
              <p>
                <strong>Género:</strong>
                <%= @candidate.genre %>
              </p>
              
              <p>
                <strong>Nivel educativo:</strong>
                <% @candidate.education_levels.each do |e| %>
                  <p><%= e.name %></p>
                <% end %>
              </p>

              <p>
                <strong>Carrera:</strong>
                <% @candidate.careers.each do |c| %>
                  <p><%= c.name %></p>
                <% end %>
              </p>
              
              <p>
                <strong>Estatus:</strong>
                <%= @candidate.status %>
              </p>
              
              
              <p>
                <strong>Idiomas:</strong>
                <% @candidate.languages.each do |l| %>
                  <p><%= l.name %></p>
                <% end %>
              </p>
              
              <p>
                <strong>Áreas de desempeño:</strong>
                <% @candidate.performance_areas.each do |p| %>
                  <p><%= p.name %></p>
                <% end %>
              </p>
              
              <p>
                <strong>Industria:</strong>
                <% @candidate.industries.each do |i| %>
                  <p><%= i.name %></p>
                  <% end %>
              </p>
              
              <p>
                <strong>Candidato regional:</strong>
                <%= @candidate.regional_candidate %>
              </p>
              
              <p>
                <strong>Estado civil:</strong>
                <%= @candidate.civil_status %>
              </p>
              
              <p>
                <strong>Skills:</strong>
                <% @candidate.skills.each do |s| %>
                  <p><%= s.name %></p>
                <% end %>
              </p>
              
              <p>
                <strong>Dispuesto a reubicarse:</strong>
                <%= @candidate.relocate %>
              </p>
              
              <p>
                <strong>Dispuesto a reubicarse:</strong>
                <%= @candidate.relocate %>
              </p>
              
              <p>
                <strong>Fuente de reclutamiento:</strong>
                <%= @candidate.recruitment_source %>
              </p>
              
              <p>
                <strong>Dispuesto a reubicarse:</strong>
                <%= @candidate.relocate %>
              </p>
              
              <p>
                <strong>Salario actual / Último salario (USD):</strong>
                <%= @candidate.actual_salary %>
              </p>
              
              <p>
                <strong>Salario variable (USD):</strong>
                <%= @candidate.variable_salary %>
              </p>
              
              <p>
                <strong>Aspiración salarial (USD):</strong>
                <%= @candidate.wage_aspiration %>
              </p>
              
              <p>
                <strong>Posición / Cargo actual:</strong>
                <%= @candidate.position %>
              </p>
              
              <p>
                <strong>Datos cuadro comparativo:</strong>
                <%= @candidate.comparative_chart %>
              </p>
              
              <p>
                <strong>Beneficio específico:</strong>
                <%= @candidate.specific_benefit %>
              </p>
              
              <p>
                <strong>Beneficios generales:</strong>
                <%= @candidate.general_benefits %>
              </p>
              
              <p>
                <strong>Comentarios generales:</strong>
                <%= @candidate.general_comments %>
              </p>
              
              <p>
                <strong>Dirección:</strong>
                <%= @candidate.address %>
              </p>
              
              <p>
                <strong>Condiciones para moverse:</strong>
                <%= @candidate.conditions_to_move %>
              </p>
              
              <p>
                <strong>Teléfono de casa:</strong>
                <%= @candidate.telephone %>
              </p>
              
              <p>
                <strong>Fecha de entrevista:</strong>
                <%= @candidate.interview_date %>
              </p>
              
              <p>
                <strong>Nacionalidad:</strong>
                <%= @candidate.nationality %>
              </p>

              <p>
                <strong>País:</strong>
                <%= @candidate.country_code %>

              </p>
              
              <div class="btn-group text-center" style="max-width: 20%">
                <%= link_to 'Editar', edit_candidate_path(@candidate), class: "btn btn-warning" %>
                <%= link_to 'Regresar', candidates_path, class: "btn btn-info" %>
              </div>
        </div>  
    </div>
  </div>
</div>